# Test against this version of Node.js
environment:
  nodejs_version: "6.3.0"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm install -g npm@next
  - npm --version
  - cd tests
  - npm install
  - npm test

# Don't actually build.
build: off
